### ISSUE TITLE
Allow config.landrush.tld to accept an array of TLDs or be defined multiple times

### ISSUE THREAD

**Issue by chrisfu** [vagrant-landrush/landrush#152] opened 2016-01-11 11:22 UTC
Hi guys,

I've got a use case where it'd be advantageous to be able to define >1 TLD within the Landrush config block. For me (and our new client), this is to support dev hostnames statically for an old web app that now has new (more sensible) hostnames defined. The idea is to keep the old hostnames and in turn their dev TLD supported until they refactor their scripts to use the newly set dev hostnames/TLD.

I've set their old TLD manually in El Capitan via /etc/resolver/old.tld with success, but obviously it'd be nicer if this were to be managed via Landrush/Vagrant auto-magically.

Unsure whether the preference for such a request would be to accept an array as input or instead use multiple config.landrush.tld lines, but that's more of a decision (pending acceptance of the use case) for the project leaders and community-at-large.

Cheers!

Chris Merrett

**Comment by bexelbie** [comment] 2016-01-11 12:15
I think the use case is reasonable.  I would prefer to keep the Vagrantfile as simple as possible.  My "first cup of coffee" feeling is that we should have multiple lines, not an array.

**Comment by chrisfu** [comment] 2016-01-12 13:12
That sounds good to me and to be honest, multi-line is what I'm more used to seeing in other Vagrant plugins anyway.

**Comment by alberttwong** [comment] 2016-03-03 23:20
Just curious, did this feature get implemented?

**Comment by bexelbie** [comment] 2016-03-07 15:26
@alberttwong this has not yet merged.  It is on the Roadmap now

**Comment by mheiges** [comment] 2016-05-18 18:14
There's a PR #125 for this. It uses an array - so I can loop over the TLDs for additional configuration.

**Comment by hferentschik** [comment] 2018-09-18 09:01
Duplicate of issue #177

**Closed by hferentschik** 2018-09-18 09:01 UTC
Labels: kind/feature, priority/major
