### ISSUE TITLE
On Fedora register host DNS with NetworkManager

### ISSUE THREAD

**Issue by bexelbie** [vagrant-landrush/landrush#260] opened 2016-09-06 10:54 UTC
Right now NetworkManager rewrites /etc/resolv.conf and overwrites our entry when there is a network change (for example from work to home networks).

**Comment by hferentschik** [comment] 2016-09-16 19:15
Any pointers on how to do this?

**Comment by hferentschik** [comment] 2018-09-05 11:49
Duplicate of issue #274

**Closed by hferentschik** 2018-09-05 11:49 UTC
Labels: kind/task, priority/major, resolution/duplicate
