### ISSUE TITLE
Unable to Install on Fedora 23

### ISSUE THREAD

**Issue by rkgade** [vagrant-landrush/landrush#184] opened 2016-05-15 22:53 UTC
Please find below the command and the error output. Any help is much appreciated.
Tried gem install hitimes, even that failed. Vagrant version 1.8.1 is installed, but through gem, only 1.5 could get installed. Also _NoMethodError_ is popping up.

    [rgade@rajkiran openshift]$ vagrant  plugin install landrush
    Installing the 'landrush' plugin. This can take a few minutes...
    Bundler, the underlying system Vagrant uses to install plugins,
    reported an error. The error is shown below. These errors are usually
    caused by misconfigured plugin installations or transient network
    issues. The error from Bundler is:

    An error occurred while installing vagrant (1.8.1), and Bundler cannot continue.
    Make sure that `gem install vagrant -v '1.8.1'` succeeds before bundling.

    NoMethodError: undefined method `spec' for nil:NilClass

**Comment by hferentschik** [comment] 2016-05-16 10:47
> vagrant verison 1.8.1 is installed, but through gem, only 1.5 could get installed.

What exactly do you mean with that?

**Comment by hferentschik** [comment] 2016-05-18 09:11
BTW, hitimes is not even a dependency of Landrush. Do you have any other plugins installed? I recommend uninstalling and then reinstalling all required plugin. 

I have seen similar errors before, but not only with Landrush. As the error suggest the error was in this cases caused by other plugins which were not properly installed.

**Comment by rkgade** [comment] 2016-05-18 09:15
Ok. There are few other plugins, but they  were installed for RedHat CDK. I believe their installation is successful.

When I am trying to install vagrant with gem command, v 1.5 is getting installed. However, through package installation, I was able to install vagrant v1.8.1 .

The error said "Make sure that `gem install vagrant -v '1.8.1'` succeeds before bundling". But I was not able to install v1.8.1 with that command.

However, now that you have said, I shall try it on a fresh vm and get back to you.
Thank you.

**Comment by hferentschik** [comment] 2016-05-18 10:26
> However, now that you have said, I shall try it on a fresh vm and get back to you.

+1

**Comment by hferentschik** [comment] 2016-06-09 18:12
Closing this. Cannot reproduce.

**Closed by hferentschik** 2016-06-09 18:12 UTC
