### ISSUE TITLE
Use semantic versioning moving forward

### ISSUE THREAD

**Issue by ezekg** [vagrant-landrush/landrush#181] opened 2016-04-22 13:50 UTC
It would be great if Landrush would follow [semantic versioning](http://semver.org) moving forward. I was taking a look at your roadmap, which mentions plans to jump from `0.20.0` to `0.90.0`, which doesn't make any sense and is hard to account for when Landrush is a dependency.

Most important bit of semver.org:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.

Here's the roadmap as it is now, just for clarification:
> ## RoadMap
> 
> The committers met and have set a basic roadmap as of 3 March 2016:
> 
> 1. 0.19 will be released as soon as possible.  The goal is to make newer
> code commits available and document the release process.
> 
> 2. Release 0.20 will occur soon.  We would like to try to land two PRs:
> 
>   * PR #125 - Multiple TLDs
>   * PR #144 - Cucumber Acceptance Tests
> 
>   The release goal is by 1 April 2016
> 
> 3. Release 0.90 (or 1.0) will occur afterward.  Goals:
> 
>   * PR #122 - Enhanced IP/NIC selection
>   * PR #154 Windows support for EventMachine/DNS
>     * We need your help, eventmachine has not proven to be very stable.
>     * Can we find an alternative to RubyDNS?  Should we try something
>       in Go or another contained cross-platform binary?
>     * This would deal with the RubyDNS dependency tree and challenges
>   * PR #160 - Cygwin Fix
> 
> 4. With Release 0.90 or 1.0 or later
> 
>   * PR #62 - Arbitrary record types

Makes everybody's life easier. 😀

**Comment by hferentschik** [comment] 2016-04-22 20:57
+1 I also think adopting semantic versioning moving forward. For that reason, I suggest to let the next release be 1.0.0 and apply semantic versioning from then on.

Regarding the roadmap, it needs updating either way.

**Comment by hferentschik** [comment] 2016-05-18 08:57
Duplicate of issue #67. Version 1.0.0 is released now and moving forward we will apply semantic versioning.

**Closed by hferentschik** 2016-05-18 08:57 UTC
