### ISSUE TITLE
Landrush blocks vagrant process when vagrant fails 

### ISSUE THREAD

**Issue by KingCrunch** [vagrant-landrush/landrush#104] opened 2015-03-18 20:08 UTC
When for example `vagrant up` fails for some reason it seems, that Landrush blocks the previous process (--> don't let it terminate properly).

```bash
$ vagrant up
# ..... something that fails
$ vagrant up # can be any vagrant action
Bringing machine 'vagrant' up with 'virtualbox' provider...
An action 'up' was attempted on the machine 'vagrant',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.

If you believe this message is in error, please check the process
listing for any "ruby" or "vagrant" processes and kill them. Then
try again.
$ ps aux | grep vagrant
sebasti+  4282  0.0  0.3 401248 49584 ?        Sl   21:03   0:00 ruby /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant up
sebasti+  4769  0.0  0.0  11200  2244 pts/0    S+   21:05   0:00 grep --color=auto vagrant
```

The reason I think landrush is the reason is, that when I stop landrush manually afterwards

```bash
$ vagrant landrush stop
```

everythings works fine again

**Comment by twisty7867** [comment] 2015-05-13 17:43
+1 

Experiencing the same here. If provisioning fails, vagrant is stuck until I kill it manually or do `vagrant landrush stop`. 

* Vagrant 1.7.2
* landrush 0.18.0. 
* host: OS X 10.10.3
* guests: 2x Ubuntu 14.04

**Comment by KingCrunch** [comment] 2015-05-16 17:56
Hi,

I can still reproduce this issue easily, but still don't know how to tell, what's the actual reason. If somebody can give me a hint how I can debug landrush/vagrant/both-in-combination I can probably give you some more information.

**Comment by ahpook** [comment] 2015-05-20 21:33
You can debug the vagrant up just by running `vagrant --debug up` ; there will also be a Landrush-specific logfile under `~/.vagrant.d/data/landrush/log/Landrush-Server.log` which may have useful info. Please make a gist with the output if you see anything useful!

**Comment by denmat** [comment] 2015-05-25 10:02
Confirmed.
Vagrant 1.7.2
OSX: 10.10.3
Gems:
```
landrush (0.17.0)
rubydns (0.9.4)
celluloid (0.16.0)
celluloid-io (0.16.1)
rexec (1.6.3)
rainbow (2.0.0)
nio4r (1.1.0)
timers (4.0.1)
hitimes (1.2.2)
```
debug log: https://gist.github.com/denmat/8226c2366cf6f23fae35

When I do ```vagrant up/reload``` it starts two processes.  You can see one at 7:52 (93408) is kicked off after the first. The one that exits at the end of the vagrant up/reload is 7:51(93301).
```
$ ps aux |grep ruby
denmat   93408   0.0  0.3  2559716  48324   ??  S     7:52pm   0:00.39 ruby /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant --debug reload --provision mp_web
denmat   93301   0.0  0.4  2560208  70256 s002  S+    7:51pm   0:06.83 ruby /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant --debug reload --provision mp_web
```

```
$ vagrant landrush stop
[landrush] Stopping daemon...
[landrush] Daemon status: stopped
$ ps aux |grep ruby
denmat   92881   0.0  0.0  2432772    668 s002  S+    7:34pm   0:00.00 grep ruby
```

Landrush-Server.log
startup:
```
=== Log Marked @ 2015-05-25 19:09:06 +1000 ===
I, [2015-05-25T19:09:06.894583 #92343]  INFO -- : Starting RubyDNS server (v0.9.4)...
I, [2015-05-25T19:09:06.895281 #92343]  INFO -- : <> Listening on udp:0.0.0.0:10053
I, [2015-05-25T19:09:06.899239 #92343]  INFO -- : <> Listening on tcp:0.0.0.0:10053
```
stopping produces (nothing else in logs):
```
=== Daemon Stopping @ 2015-05-25 19:34:21 +1000 ===
W, [2015-05-25T19:34:21.980971 #92343]  WARN -- : Terminating task: type=:call, meta={:method_name=>:run}, status=:iowait
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
W, [2015-05-25T19:34:21.981629 #92343]  WARN -- : Terminating task: type=:call, meta={:method_name=>:run}, status=:iowait
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
```

If I stop ```$ vagrant landrush stop/start``` it vagrant up/halt/provision commands work and the process list for ruby looks like this:
```
$ ps aux |grep ruby
denmat   93166   0.0  0.0  2432772    668 s002  S+    7:40pm   0:00.00 grep ruby
denmat   92908   0.0  0.2  2539604  30524   ??  S     7:36pm   0:00.64 ruby /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant landrush start
```

Reproducible each time.

**Comment by denmat** [comment] 2015-05-25 10:59
I have narrowed down the failing behaviour.

With this Vagrantfile:
```
Vagrant.configure('2') do |config|
  config.landrush.enabled = true
  config.landrush.tld = '.test'
  config.vm.define :test do |conf|
    conf.vm.box = 'ubuntu/precise64'
    conf.vm.provision "shell",
        inline: 'exit 1'
  end
end
```

Reproducible steps for error:
```
$ vagrant up --provision
$ vagrant provision
```
Steps for a work around:
```
$ vagrant up
$ vagrant provision
```
I've updated the above gist with the output from ```$ vagrant --debug provision``` from this test case (and removed the previous)

Setting either ```config.landrush.enabled = false``` or 
```
   conf.vm.provision "shell",
        inline: 'exit 0'
```
produces expected valid results.

**Comment by peterfarrell** [comment] 2015-06-09 19:51
We are seeing this same issue all the time if provisioning fails.

**Comment by cintiadr** [comment] 2015-07-31 00:54
OS X 10.10, Vagrant 1.7.2, landrush (0.15.3) vagrant plugin, same problem.

**Comment by hferentschik** [comment] 2016-06-22 18:34
Can anyone verify whether this is still an issue with Landrush 1.0.0

**Comment by madAndroid** [comment] 2016-06-23 05:59
@hferentschik - I can confirm this is working with:

OSX 10.11.4
Vagrant 1.8.4
Landrush 1.0.0

I was able to reproduce previously with the steps outlined above, but now it appears to be solved.
Awesome work! this has been a long time coming :)

**Comment by hferentschik** [comment] 2016-06-23 07:20
Ok, closing this then.

**Closed by hferentschik** 2016-06-23 07:20 UTC
