### ISSUE TITLE
invalid byte sequence in UTF-8 on non-english windows platform

### ISSUE THREAD

**Issue by Valgard** [vagrant-landrush/landrush#309] opened 2017-03-17 18:46 UTC
landrush raises an exception on my german windows 10 with following message

.../.vagrant.d/gems/2.2.5/gems/landrush-1.2.0/lib/landrush/cap/host/windows/configure_visibility_on_host.rb:150:in `wired_autoconfig_service_running?': invalid byte sequence in UTF-8 (ArgumentError)

**Comment by hferentschik** [comment] 2018-09-13 08:14
I think this is a duplicate of #310.

**Closed by hferentschik** 2018-09-13 08:14 UTC
